### PR TITLE
Cleanup and Fix

### PR DESCRIPTION
**Pull request by acu192**
Changes:

- Updated the main `README.md` file to contain clear instructions for how to install everything (i.e. how to clone, create an environment, set up JupyterLab, install this repo's backend, and install this repo's frontend).

- Moved the `IMetadataApolloGraphQlConnection` interface into its own file inside the `src/metadata_iface` directory. (It used to be in the _same_ file as the implementation. This change makes it consistent with how the other interfaces are organized.)

- Fixed (I think!) the Jupyter Server Proxy `_xsrf` issue. Queries now are being run through Jupyter Server Proxy to Apollo, and results are returned back successfully.

- Removed hard-coded test data (and removed two corresponding helper functions which were no longer being used).

- Removed some small stale comments (comments that spoke of things that were no longer true).

### CODE REVIEW

**Comment by xmnlab** [comment]
that is awesomw @acu192 ! thanks! could you fix the conflict on comments?

**Comment by acu192** [comment]
Regarding the `_xsrf` fix, here is what I discovered:

(Disclaimer: I didn't fully dive down into this issue, but I discovered a few interesting things that led to the fix. We'd want to look at this further to _fully_ understand what is happening...)

JupyterLab, by default, uses a random token to authenticate browser sessions, and the browser will send a header with that token (like shown below) with every API call:
```
Authorization: token yourrandomtokenhere9282
```

That code that does that is [here](https://github.com/jupyterlab/jupyterlab/blob/a99cfda0466fd6cf15a77b434e66811c1ec2c53c/packages/services/src/serverconnection.ts#L260).

Then the Notebook server will check for this token. If it doesn't find it, it will ask Tornado to check the `XSRF` cookie (I think that's where our previous error came from; see [here](https://github.com/jupyter/notebook/blob/8a4cbd0ad91371392b90672afea58560d37c847e/notebook/base/handlers.py#L404)). If it _does_ find the token, it doesn't check for the `XSRF` token.

That all makes sense, and I was going to have Apollo send this same header for us, as is shown in the documentation [here](https://www.apollographql.com/docs/react/recipes/authentication.html).

However, before doing that I tried what that link above suggests of just adding `credentials: 'same-origin'` to the ApolloClient config, and that seemed to make it all work!

Honestly I still don't know why that works. If needed, we can _also_ add the code to make Apollo Client includes the token in every request, like JupyterLab does... but for now I figure we should wait on that to see if we find anything else out about what is happening to make this current fix work.

Here's another bit of info: The Jupyter Server Proxy requires all requests be authenticated, see [here](https://github.com/jupyterhub/jupyter-server-proxy/blob/21078100adbde5f8d3560192eb742eca22961013/jupyter_server_proxy/handlers.py#L380). One theory I have is that somewhere there is code to use the request's session id (which is stored and sent as a cookie in every request sent by the Apollo Client) to look up and set the token somewhere deep inside Jupyter (Proxy?) Server. The code I added to fix this says that it causes cookies to be included in each request, so that's where this theory comes from.

**Comment by acu192** [comment]
If someone wants to verify this works on their machine:

```bash
git clone https://github.com/jupyterlab/jupyterlab.git
git clone -b apollo_ryan https://github.com/Quansight/jupyterlab-metadata-service.git

conda create -n jupyterlab-metadata-service -c conda-forge notebook
source activate jupyterlab-metadata-service

# Backend
cd jupyterlab-metadata-service/backend
pip install -e .
cd jupyterlab_metadata_service_server
npm install
cd ../../..

# JupyterLab and Frontend
cd jupyterlab
pip install -e .
jlpm run add:sibling ../jupyterlab-metadata-service/frontend
jupyter lab --watch --dev
```

Then open the "Metadata" widget (using the command pallet). If you see JSON print out to the Widget, that means it is working! Let me know!

**Comment by xmnlab** [comment]
that is aweseome!Thanks @acu192 !

**Pull request merged**
